### PR TITLE
[FIX] stock_picking_report_valued: division_by_zero when unrelated sale order

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]

**Review by victor-ditay — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Even better now

**Comment by emagdalenaC2i** [comment]
Are this ready to merge?

**Comment by carlosdauden** [comment]
Don't merge yet, I want to think about it

**Comment by pedrobaeza** [comment]
@emagdalenaC2i you can try the use cases by yourself if you want for being sure

**Comment by carlosdauden** [comment]
As the problem is blocking we can merge and if I think of a better way I open a new PR

**Comment by emagdalenaC2i** [comment]
ok, I'll try it this weekend and report any issues

**Review by emagdalenaC2i — APPROVED** [review]
Tested in runbot

**Review by rousseldenis — APPROVED** [review]

**Pull request closed without merging**
