### PR TITLE
[ADD] stock_valued: Add amount information to pickings

### PR DESCRIPTION
**Pull request by acysos**
Hello,

Add price, discounts, untaxed amount, taxes and total to picking list.

Greetings

### CODE REVIEW

**Comment by clonedagain** [comment]
Technically this changes a "report" indeed, but it's not really reporting is it?
Maybe it would be best suited in stock-logistics-warehouse?

**Comment by acysos** [comment]
Hello,

Yes, this module modify the stock.picking report, add prices, taxes and total to this report, if the partner has the option stock valued checked.

If you think that is better in other repository, no problem I close this PR and send a new to the other repository.

Greetings

**Comment by pedrobaeza** [comment]
Well, I see that this repo is the more suitable. Equal to stock picking webkit report, that modifies standard one to make it work with Webkit engine.

Ignacio, I have to pass you one modified version of this module (including name), that enhances this one.

**Comment by angelmoya** [comment]
I think will be better to do two modules:
- stock_valued, in stock-logistics-warehouse
- stock_valued_report, that depends to stock_valued, in this repo

**Comment by pedrobaeza** [comment]
We have semi-migrated a better version of this module in my repo: https://github.com/serviciosbaeza/odoo-addons/pull/4. Please check that one, and let's complete it with the qweb report instead. This don't need the split, because you can choose by partner if you want a valued picking or not.

**Comment by acysos** [comment]
I think that it's not neccesary split in two module. This module work and use the new api, but for the moment I don't continue the development, because I have other priority modules. If some one have time to merge the improvement that  say Pedro, it can be done.

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
As it seems there's no interest, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
