### PR TITLE
[15.0][MIG] delivery_line_sale_line_position

### PR DESCRIPTION
**Pull request by ajaniszewska-dev**

### CODE REVIEW

**Review by grindtildeath — APPROVED** [review]
:+1:

**Review by ivantodorovich — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Comment by ajaniszewska-dev** [comment]
@pedrobaeza  this one also ready to merge if you can, thank you

**Comment by pedrobaeza** [comment]
Please change PR title as stated in the other PR

**Comment by ajaniszewska-dev** [comment]
> Please change PR title as stated in the other PR

@pedrobaeza  i think it's good now. Sorry for that.

**Pull request merged**
