### PR TITLE
12.0 mig stock picking comment template

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
Standard migration

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@pedrobaeza, @xavierjimenez and @cubells Please, could you review this PR?

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by rousseldenis — APPROVED** [review]
Code review.

Note for next version that base module should be IMHO migrated to server-ux repo (not to pull account-invoice-reporting one)

**Pull request closed without merging**
