### PR TITLE
[15.0] [MIG] stock_report_quantity_by_location

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
Hi @JasminSForgeFlow 

I am suggesting some changes in V13 (https://github.com/OCA/stock-logistics-reporting/pull/204). Maybe you agree with what I am suggesting :)

**Comment by JasminSForgeFlow** [comment]
> Hi @JasminSForgeFlow
> 
> I am suggesting some changes in V13 (#204). Maybe you agree with what I am suggesting :)

Yes, Agree.
It will give more details

**Comment by JuanyDForgeflow** [comment]
@JasminSForgeFlow Are you going to add the code from https://github.com/OCA/stock-logistics-reporting/pull/204/ ? Everything else is working fine

**Comment by JasminSForgeFlow** [comment]
Added https://github.com/OCA/stock-logistics-reporting/pull/204 changes

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional

**Pull request merged**
