### PR TITLE
[15.0][MIG]stock_account_valuation_report

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
No changes needed

@ForgeFlow 
@JoanMForgeFlow
@BernatPForgeFlow

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Could you check pre-commit ?

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
