### PR TITLE
[14.0][MIG] stock_inventory_valuation_pivot

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Functional test OK

**Comment by pedrobaeza** [comment]
Next time please check before doing this wild merge. There was #206, and this migration doesn't seem correct. Please check the migration diff from the other PR:

https://github.com/OCA/stock-logistics-reporting/pull/206/commits/c5144957c4079825882ad2cc113d766b5f6aed93

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza see https://github.com/OCA/stock-logistics-reporting/pull/215

**Pull request merged**
