### PR TITLE
[12.0] [MIG] stock_move_value_report: Migration to v12.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT25251

This module allows to obtain a report with the cost of a given operation. On next screenshot you can see an example of the option for print a transfer.
image

Please @chienandalu @victoralmau can you review this?

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by victoralmau — APPROVED** [review]

**Review by ernestotejeda — COMMENTED** [review]
I think 'Customer Address' is not displaying correctly.
Tested in runbot.

**Comment by chienandalu** [comment]
> I think 'Customer Address' is not displaying correctly.
> Tested in runbot.

Did you check if it happens in a the main branch runbot as well? Maybe it comes from another module issue

**Comment by chienandalu** [comment]
> > I think 'Customer Address' is not displaying correctly.
> > Tested in runbot.
> 
> Did you check if it happens in a the main branch runbot as well? Maybe it comes from another module issue

Thinking twice, maybe it's due to classes not migrated from BS3 to BS4. @CarlosRoca13 can you check?

**Comment by CarlosRoca13** [comment]
@chienandalu I'm checking right now what's happening

**Comment by CarlosRoca13** [comment]
Changes of bootstrap done! @chienandalu @ernestotejeda you can see on this image the result.
image
I add the address of customer too.

**Review by chienandalu — APPROVED** [review]
Ok, great :)

**Pull request merged**
