### PR TITLE
[13.0][MIG]stock_account_valuation_report

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Todo:

- [x] get back the filtering by date feature
- [x] add a test
- [x] include improvements on https://github.com/OCA/stock-logistics-reporting/pull/158

cc @ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Sorry, this is wrong.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
don't close this bot please

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
