### PR TITLE
[13.0] [MIG] stock_picking_report_custom_description: Migration to v13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT22092

Please @carlosdauden @sergio-teruel, can you review this?

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]

**Comment by rousseldenis** [comment]
IMHO, the module name does not reflect what it does in reality. Could you improve it (and README)?

**Review by sergio-teruel — COMMENTED** [review]
Maybe this module not needed for v13.0
ping @carlosdauden @pedrobaeza 

https://github.com/odoo/odoo/blob/c61db20204700a375f7005f50f95b44a60c3bb70/addons/stock/report/report_deliveryslip.xml#L46-L49

Now, Odoo display the description when is diffrent to product name... (for stock move origin)

But for picking in done state.... maybe need it...
https://github.com/odoo/odoo/blob/c61db20204700a375f7005f50f95b44a60c3bb70/addons/stock/report/report_deliveryslip.xml#L71-L76

**Review by sergio-teruel — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
ping @carlosdauden

**Comment by carlosdauden** [comment]
This module is not necessary in v13. we can close this PR.

**Comment by carlosdauden** [comment]
Can you open a new PR to add in apriory file:
https://github.com/OCA/OpenUpgrade/blob/13.0/odoo/addons/openupgrade_records/lib/apriori.py#L66-L67
This code:
```
    # OCA/stock-logistics-reporting
    'stock_picking_report_custom_description': 'stock',

```
?

Thanks.

**Comment by CarlosRoca13** [comment]
Ok! For sure @carlosdauden

**Pull request closed without merging**
