### PR TITLE
 [17.0][MIG] stock_report_quantity_by_location 

### PR DESCRIPTION
**Pull request by AMhadhbi**
nothing to do

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! Every migration PR needs a migration commit. Even if no files need to be changed, it is in this commit that the version number is bumped. In your branch, the version bump happens in the pre-commit commit. That is not according to the procedure. Can you fix that, and can you also squash out pandoc-3.2-x86_64-macOS.pkg?

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Please check my comments above

**Comment by rousseldenis** [comment]
@AMhadhbi

**Comment by PieterPaulussen** [comment]
Superseeded this PR and fixing the comments from @StefanRijnhart: https://github.com/OCA/stock-logistics-reporting/pull/344.

(@AMhadhbi Sorry to hijack the migration but I needed this fix for a project and was not able to wait for the fix.)

**Comment by StefanRijnhart** [comment]
Closing in favor of https://github.com/OCA/stock-logistics-reporting/pull/344

**Pull request closed without merging**
