### PR TITLE
[13.0][MIG] stock_picking_report_custom_description: Migration to v13.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36927

ping @chienandalu

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Odoo/OCB tests failing on loading the views

**Comment by ernestotejeda** [comment]
@sergio-teruel  I got the same failure migrating from 12 to 14 (https://github.com/OCA/stock-logistics-reporting/pull/209). I solved it by changing the xpath expression to locate the field, apparently another module changes the view before our module inherits from it.

**Comment by sergio-teruel** [comment]
@ernestotejeda Thanks!! Fixed

**Comment by pedrobaeza** [comment]
@chienandalu can you re-review?

**Review by chienandalu — APPROVED** [review]

**Review by ernestotejeda — APPROVED** [review]

**Pull request merged**
