### PR TITLE
[IMP] stock_picking_report_summary : Add test

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial PR. Just add test.

### CODE REVIEW

**Review by quentinDupont — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍 

@OCA/logistics-maintainers this could be merged 😄 already 3 approvals

**Review by hparfr — APPROVED** [review]
/ocabot merge minor

**Comment by legalsylvain** [comment]
@hparfr : I rebased, could retry ?

**Pull request merged**
