### PR TITLE
[15.0][MIG] stock_picking_report_valued_sale_mrp: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT37322

Main changes:
- Disable printing of kits in a separate table implemented in odoo core mrp module
- Adapt  the template report redefinition

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @chienandalu

**Review by chienandalu — APPROVED** [review]
Great job! :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
