### PR TITLE
[16.0][mig] stock_card_report: Migration to 16.0

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by andyjquijada — APPROVED** [review]
The code LGTM

ping @pedrobaeza

**Comment by Pablocce** [comment]
Functional and technical review LGTM

**Review by Pablocce — APPROVED** [review]
Functional and technical review, LGTM!

**Review by RodrigoBM — APPROVED** [review]

**Comment by RodrigoBM** [comment]
is it possible to merge this, @OCA/logistics-maintainers, thank you

**Comment by RodrigoBM** [comment]
ping @dreispt

**Pull request merged**
