### PR TITLE
[13.0][FIX] E741 ambiguous variable name 'l'

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be avoided with ~~#665~~, but well, it's always good to have it changed as good practice.

**Comment by rousseldenis** [comment]
> This should be avoided with #665, but well, it's always good to have it changed as good practice.

Could you include the good link ?

**Comment by pedrobaeza** [comment]
Sorry, it can't be relative...

It's https://github.com/OCA/maintainer-quality-tools/pull/665

**Review by feketemihai — APPROVED** [review]

**Comment by feketemihai** [comment]
@pedrobaeza can you merge this one, please, seems that https://github.com/OCA/maintainer-quality-tools/pull/665 didn't fixed the issue, see https://github.com/OCA/stock-logistics-reporting/pull/109

**Pull request merged**
