### PR TITLE
[MIG] stock_analysis: Migrate to version 10.0

### PR DESCRIPTION
**Pull request by omejia26**
Hi,  i hope it can be useful

This is the update from related module https://github.com/OCA/stock-logistics-reporting/pull/22,  in this version the location is on  **Inventory > Reports**

### CODE REVIEW

**Comment by eLBati** [comment]
@omejia26 thanks. Why commits about ```stock_analysis_forecast``` are present? Did you follow the procedure
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch
?

Please not note, in this case, as ```stock_analysis``` is not released for 9.0, in the procedure you have to replace ```9.0``` with ```8.0```

```
git format-patch --keep-subject --stdout origin/10.0..origin/9.0 -- $MODULE | git am -3 --keep
```
becomes
```
git format-patch --keep-subject --stdout origin/10.0..origin/8.0 -- $MODULE | git am -3 --keep
```

**Comment by rousseldenis** [comment]
@omejia26 Do you plan to finish this ?

**Comment by eLBati** [comment]
Porting to 12 with https://github.com/OCA/stock-logistics-reporting/pull/90

**Comment by rousseldenis** [comment]
@omejia26

**Pull request closed without merging**
