### PR TITLE
[15.0][ADD] stock_picking_report_external_note

### LINKED ISSUE #264: [15] stock_picking_client_note (or maybe stock_picking_external_note)
We need to add a text field `note` in stock picking to be printed in delivery slip. The development is really simple.

- [x] Create a new field client_note (html) in the same way note is created in core
- [x] Print this new field in client delivery slip

I know already all the alternatives and no one is the requirement.

- ~~https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_comment_template~~ when you have templates or comments. In this use case every comment is different in each picking
- ~~https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_report_custom_description~~ bring the description of sales to picking
- ~~https://github.com/OCA/stock-logistics-workflow/tree/14.0/stock_delivery_note~~ depends on delivery module

Odoo has a field note for internal comments for each picking which are only printed in picking operations

We need a external one to be printed only in delivery slip and not from sale order or any other related document

We will make a PR soon.

@moduon MT-2153

Regards

### PR DESCRIPTION
**Pull request by Shide**
New module to displan a note on the Deliver Slip report.

This module doesn't have any "rare" dependency. 
Just a new field (html, not text) and inherit on the Delivery Slip report.

resolves #264 

MT-2153 @moduon @yajo @rafaelbn @anddago78 please review if you want :)

### CODE REVIEW

**Comment by Shide** [comment]
closes #264

**Comment by rousseldenis** [comment]
@Shide Thanks for this. I think there is already such module. I'll try to find out where it is.

**Comment by Shide** [comment]
I find https://github.com/OCA/stock-logistics-workflow/tree/14.0/stock_delivery_note but this module is intended to be used as a delivery note for the transport company, not for the customer (because the delivery dependency).

**Comment by rousseldenis** [comment]
> I find https://github.com/OCA/stock-logistics-workflow/tree/14.0/stock_delivery_note but this module is intended to be used as a delivery note for the transport company, not for the customer (because the delivery dependency).

Yes I saw the comment. But I'm quite sure there is something

**Comment by rousseldenis** [comment]
There is:

- https://github.com/OCA/stock-logistics-reporting/pull/57

But maybe too much code. This one is more simple

**Comment by rafaelbn** [comment]
Hello @rousseldenis !

As you can check here https://github.com/OCA/stock-logistics-reporting/issues/264 I analysed all before making the PR, I Opened issue time ago 😄 

> I know already all the alternatives and no one is the requirement.
> 
> https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_comment_template when you have templates or comments. In this use case every comment is different in each picking
> https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_report_custom_description bring the description of sales to picking
> 

About you comment 

> But maybe too much code. This one is more simple

Not only much more simple,

- Is different functionality
- You could need both at the same time

Thank you very much for you review! ❤️

**Comment by rousseldenis** [comment]
> Hello @rousseldenis !
> 
> As you can check here #264 I analysed all before making the PR, I Opened issue time ago smile
> 
> > I know already all the alternatives and no one is the requirement.
> > https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_comment_template when you have templates or comments. In this use case every comment is different in each picking
> > https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_report_custom_description bring the description of sales to picking
> 
> About you comment
> 
> > But maybe too much code. This one is more simple
> 
> Not only much more simple,
> 
> * Is different functionality
> * You could need both at the same time
> 
> Thank you very much for you review! heart

Yes, I saw it. I just wondering myself why nobody proposed that already as it seems such a common needs :sweat_smile: 

So, let's move forward

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Review by anddago78 — APPROVED** [review]
For me is ok! technical y funtional review..

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @Shide 
Captura desde 2023-03-23 15-58-50
Captura desde 2023-03-23 15-58-31

**Review by rafaelbn — COMMENTED** [review]
Please @Shide add sections, label or boxes to make more clear that there are two deferent fields

Please improve a little bit it UX for recognize easily both fields

imagen

**Comment by Shide** [comment]
@rafaelbn done refactor of view

**Review by rafaelbn — APPROVED** [review]
Great! Review done! 👍 Thank you ❤️ 

Please @rousseldenis could you merge for us? 🙏

**Review by fcvalgar — APPROVED** [review]
LGTM, Thank you @Shide

**Pull request merged**
