### PR TITLE
[ADD] stock_picking_comment_template

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
Adds comments on stock picking

See #53

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@xavierjimenez and @cubells I will need some help to add the test here
If you are in the Spanish OCA Days I could meet you here

**Comment by xavierjimenez** [comment]
Hi @emagdalenaC2i , I'm at Spanish OCA Days, let me know how I can help you.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza @xavierjimenez and @cubells I think this is ready now to review and merge

**Comment by emagdalenaC2i** [comment]
@pedrobaeza @xavierjimenez Please, could you review this PR?

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by emagdalenaC2i** [comment]
@pedrobaeza @xavierjimenez and @cubells Please, could you review this PR?
Thanks

**Comment by pedrobaeza** [comment]
I'm not able to review it right now

**Comment by emagdalenaC2i** [comment]
It does not have to be right now. It's been ready for a week

**Comment by cubells** [comment]
@pedrobaeza @emagdalenaC2i 

I'll review now.

**Comment by xavierjimenez** [comment]
@emagdalenaC2i 

I have tried to install it on a new Odoo 12 community and I get the following error:

```
El elemento '<xpath expr="//table[hasclass('table-condensed')]">' no puede ser localizado en la vista padre

Contexto del error:
Vista `report_picking_document_comments`
[view_id: 1444, xml_id: n/a, model: n/a, parent_id: 1261]
None" while parsing None:5, near
<data inherit_id="stock.report_picking">
      <xpath expr="//table[hasclass('table-condensed')]" position="before">
        <p t-if="o.note1">
          <span t-field="o.note1"/>
        </p>
      </xpath>
      <xpath expr="//p[@t-field='o.note']" position="after">
        <p t-if="o.note2">
          <span t-field="o.note2"/>
        </p>
      </xpath>
    </data>
```

**Comment by emagdalenaC2i** [comment]
@xavierjimenez it is an Odoo 11 module

**Comment by xavierjimenez** [comment]
@emagdalenaC2i whoops sorry! I'll try it on an 11 then to add an review.

**Review by xavierjimenez — APPROVED** [review]
I have tested it and looks good functionally, so I approve it. 👍

**Pull request merged**
