### PR TITLE
[14.0][MIG] stock_quantity_history_location

### PR DESCRIPTION
**Pull request by atchuthan**
@SodexisTeam

### CODE REVIEW

**Review by ypapouin — APPROVED** [review]
LGTM - Code and Functional Reviews

**Review by clementmbr — APPROVED** [review]
LGTM too!

**Comment by clementmbr** [comment]
@atchuthan @ypapouin @BT-cjimeno do you think this PR can me merged ?

**Comment by atchuthan** [comment]
> @atchuthan @ypapouin @BT-cjimeno do you think this PR can me merged ?

Yes, will ask OCA maintainers to merge via discord.

**Pull request merged**
