### PR TITLE
[FIX] replace both Print buttons with the new action

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by lepistone** [comment]
original MP in launchpad: https://code.launchpad.net/~camptocamp/stock-logistic-report/7.0-replace-print-actions-mdh/+merge/225126

for the tests to pass, I will rebase on https://github.com/OCA/stock-logistics-reporting/pull/1 that fixes a problem unrelated to this branch.

**Comment by bwrsandman** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
I check I found no other inheritance on name on those buttons so we should have the same issue as in https://github.com/OCA/sale-workflow/pull/21

:+1:

**Pull request merged**
