### PR TITLE
[MIG] stock_picking_report_valued_sale_mrp: Migration to 13.0

### PR DESCRIPTION
**Pull request by chienandalu**
TT29359 cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@CarlosRoca13 @chienandalu please confirm it's OK.

**Comment by CarlosRoca13** [comment]
Yes it's ready @pedrobaeza

**Review by chienandalu — COMMENTED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
