### PR TITLE
[MIG] [16.0] stock_picking_report_external_note

### PR DESCRIPTION
**Pull request by Shide**
Straight forward migration, nothing changed

MT-6202 @moduon @EmilioPascual @Gelojr @rafaelbn @fcvalgar please review if you want :)

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @Shide

**Review by EmilioPascual — APPROVED** [review]
LGTM. Functional and code review.

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
