### PR TITLE
[16.0][MIG] stock_picking_report_valued: Migration to 16.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration to 16.0

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Functional and code review

**Review by sebalix — APPROVED** [review]

**Comment by loida-vm** [comment]
@miguel-S73 I've just review this module and I detected this error https://github.com/OCA/stock-logistics-reporting/issues/278
Could you review it?
Thanks

**Pull request merged**
