### PR TITLE
[16.0][MIG] stock_move_value_report: Migration to 16.0

### PR DESCRIPTION
**Pull request by vvrossem**
From 15.0 to 16.0, in

- `stock.picking`: `move_lines` is renamed into `move_ids` 
- `stock.move.line` : `product_qty` is renamed into `reserved_qty`

### CODE REVIEW

**Review by Camille0907 — APPROVED** [review]
Migration LGTM

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Pull request merged**
