### PR TITLE
[11.0][stock_report_quantity_by_location]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This report intends to help users to get to know the quantities on hand for multiple locations simultaneously.

image

image

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
I tried to use related + store (+index) issuing bad performance comparing to assign directly.

**Comment by JordiBForgeFlow** [comment]
@lreficent @ageficent @aheficent can you review this one, plz?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test + code review

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by rousseldenis** [comment]
@jbeficent I hope this was not WIP anymore (didn't see before launching gitbot merge...)

**Pull request closed without merging**
