### PR TITLE
[10.0][MIG]stock_account_valuation_report (WIP)

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
* The "At date" feature is removed for now. It is best to backport the "Inventory at Date" report from standard Odoo 11 and then modify it than to apply the changes directly in the query for the report in v10, which is based on quants.

cc @ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
pending to rebase after merging #127 

Edit: Rebased and green

**Comment by bodedra** [comment]
@AaronHForgeFlow Tested with Stock Journal entries 95k and it took around 45 minutes to generate report. Is there something we can work together and improve performance? Or is this expected?

Appreciate your valued contribution.

**Comment by AaronHForgeFlow** [comment]
It should not take that much. I have tested in a database with around 150K entries and it takes around 12 seconds. 

In any case, I will propably close this PR because this report is quite similar to this other report, and it is already merged: https://github.com/OCA/stock-logistics-warehouse/blob/10.0/stock_valuation_account_manual_adjustment/views/product_view.xml#L42

**Comment by bodedra** [comment]
@AaronHForgeFlow Thanks for your quick response. Let me check with your suggested.

**Comment by bodedra** [comment]
@AaronHForgeFlow It works great! Thank you.

As we use product.product object, I found two issues:

1. Net Quantity and
2. Accounting date filter.

Let's open this PR for now if you don't have any problem.

**Comment by bodedra** [comment]
@AaronHForgeFlow I have moved forward with your suggested `stock_valuation_account_manual_adjustment` module and not planning to contribute in this. If you want, you may close this PR. Thank you my friend!

**Pull request closed without merging**
