### PR TITLE
[13.0][MIG] stock_picking_report_undelivered_product: Module migration

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT27476

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Travis fails to run pre-commit..
@pedrobaeza Who can see this error?

stderr:
    ERROR: Cannot install pre-commit-dummy-package==0.0.0 and pylint-odoo==3.0.3 because these package versions have conflicting dependencies.

**Comment by pedrobaeza** [comment]
@joao-p-marques please run the copier template here.

**Comment by sergio-teruel** [comment]
Thanks!!

**Comment by joao-p-marques** [comment]
Done @pedrobaeza @sergio-teruel https://github.com/OCA/stock-logistics-reporting/pull/135

**Comment by sergio-teruel** [comment]
@pedrobaeza can you merge the https://github.com/OCA/stock-logistics-reporting/pull/135 PR to unlock this one

**Comment by pedrobaeza** [comment]
Done

**Comment by sergio-teruel** [comment]
Rebase done after https://github.com/OCA/stock-logistics-reporting/pull/135 has been merged!!

**Comment by pedrobaeza** [comment]
Is this still WIP?

**Comment by sergio-teruel** [comment]
Nooo.... Sorry!!

**Review by pedrobaeza — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
