### PR TITLE
[15.0][MIG] stock_picking_report_valued

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Review by cesar-tecnativa — APPROVED** [review]

**Review by ofonseca-pyming — APPROVED** [review]
I never liked that tax column order in valued_report_picking header but anyway.... LGTM

**Comment by pedrobaeza** [comment]
@flachica please rename latest commit message to follow standard guidelines:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

**Comment by flachica** [comment]
> @flachica please rename latest commit message to follow standard guidelines:
> 
> https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

Sorry. Message was fixed, thanks for your review @pedrobaeza

**Comment by pedrobaeza** [comment]
I'm afraid it's still not correct. Please read the link I have put, although as tip it should be something like: `[MIG] stock_picking_report_valued: Migration to 15.0`

**Comment by flachica** [comment]
Done @pedrobaeza

**Comment by pedrobaeza** [comment]
Why do you insist with `15.0.1.0.0` instead of `15.0` or `v15` that doesn't give an special meaning? And the proper commit message format is `[TAG] <module>: ...` (with 2 points).

**Comment by pedrobaeza** [comment]
I'm merging now as not being critical and don't block this, but please follow strictly guidelines (or didn't you read them?)

/ocabot merge nobump

**Comment by flachica** [comment]
> Why do you insist with `15.0.1.0.0` instead of `15.0` or `v15` that doesn't give an special meaning? And the proper commit message format is `[TAG] <module>: ...` (with 2 points).

In the guideline I read 

"Use tags as [listed in the Odoo Guidelines](https://www.odoo.com/documentation/14.0/reference/guidelines.html#tag-and-module-name) with the following extensions: - [MIG] for migrating a module"

I haven't found anything about how to name the version. And yes, I have seen that the tag issue was included last year. When someone tells me to read something interesting I do it.

**Comment by pedrobaeza** [comment]
I find this one referred from OCA guidelines to be very instructive:

imagen

Anyways, it's true that the document contains several incorrect things that I'm fixing in https://github.com/OCA/odoo-community.org/pull/68

**Pull request merged**
