### PR TITLE
[15.0] [MIG] `stock_production_lot_traceability_shipment_report`

### PR DESCRIPTION
**Pull request by ivantodorovich**
ping @damdam-s @jcoux @rousseldenis

### CODE REVIEW

**Review by jcoux — APPROVED** [review]
Technically seems good :+1:

**Review by yankinmax — APPROVED** [review]

**Comment by ivantodorovich** [comment]
@OCA/logistics-maintainers could I bother you with a merge?

**Comment by jbaudoux** [comment]
Can you make shorter commit messages?

**Comment by ivantodorovich** [comment]
> Can you make shorter commit messages?

I don't really like abbreviating the module name in the commit msg, but ok.. 
There's not much to shorten besides that 😓

**Comment by rousseldenis** [comment]
/ocabot migration stock_production_lot_traceability_shipment_report

**Comment by rousseldenis** [comment]
@ivantodorovich There's something weird in your commit history as the module exists in 12.0 but initial commit seems to be in 15.0...

**Comment by ivantodorovich** [comment]
@rousseldenis it may be due to the fact that I created this PR before 12.0 had been merged? do this create an issue somewhere?

**Pull request closed without merging**
