### PR TITLE
[MIG][12.0] stock_picking_report_custom_description: Migration to v12.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT20140
@carlosdauden @Tardo Review please

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Solving the runbot warning (not sure if related to this PR)

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The module in the second commit message is incorrect. Please fix it and I'll merge.

**Comment by sergio-teruel** [comment]
Changes done!!

**Pull request merged**
