### PR TITLE
[12.0] [ADD] `stock_production_lot_traceability_shipment_report`

### PR DESCRIPTION
**Pull request by ivantodorovich**
**Description**
Easily see which Lots/Serial Numbers were consumed or produced by/from another one.

**Usage**
Go to the form view of any Lot/Serial Number that has either been consumed or that has produced other Lots/Serial Numbers, and click on the "Consumed" or "Produced" smart buttons to navigate to these records. It will show all records, directly or indirectly consumed or produced by it.

---

Superseeds:
- https://github.com/OCA/stock-logistics-workflow/pull/1173

ping @damdam-s @jcoux @rousseldenis

### CODE REVIEW

**Review by jcoux — APPROVED** [review]
Technically seems good :+1:

**Comment by rousseldenis** [comment]
@ivantodorovich Could you rebase ?

**Comment by ivantodorovich** [comment]
Done!

**Review by rousseldenis — APPROVED** [review]
LGTM. Code review

**Pull request merged**
