### PR TITLE
[16.0][MIG] stock_picking_report_product_sticker: Migration to 16.0

### PR DESCRIPTION
**Pull request by Shide**
Minor field name fixes and added @rafaelbn as a maintainer.

MT-6567 @moduon @rafaelbn @fcvalgar @Gelojr @yajo please review if you want :)

### CODE REVIEW

**Review by edlopen — APPROVED** [review]
LGTM, thank you!

**Review by rafaelbn — APPROVED** [review]
Great thanks! 👍🏼 

Tested in staging

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @Shide

**Pull request merged**
