### PR TITLE
[11.0][IMP] stock_picking_comment_template move note1

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@pedrobaeza No idea why travis is red.
Are this a travis issue?

**Comment by pedrobaeza** [comment]
Fixed in 6a4359279bbaa07dcf18993ecd719783e30b9106. Please rebase.

**Review by rousseldenis — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
@pedrobaeza could you review and approbe this PR?

**Comment by pedrobaeza** [comment]
Sorry, I can't review all the PRs that come to OCA. I let other reviewers interested in this feature.

**Comment by emagdalenaC2i** [comment]
No, sorry @pedrobaeza . I know you have a lot of things to do. Thanks

@xavierjimenez and @cubells This is a minor improvement just to keep the same format than in quotations and invoices. Please, could you review and approbe this PR?

**Comment by emagdalenaC2i** [comment]
The only think changed with this PR is the position of the comment to keep the same format than quotations and invoices
image
Please, @xavierjimenez and @cubells could review and approve this PR?

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Pull request merged**
