### PR TITLE
[16.0][ADD] stock_picking_report_header_repeater: New module to repeat the header in all pages of the delivery report

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT49244

ping @sergio-teruel @pilarvargas-tecnativa

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Comment by EmilioPascual** [comment]
Why change the report?
In odoo core the addresses appear at the beginning.
image

But in your report the address is shown below the shipping date.
image

**Review by Shide — CHANGES_REQUESTED** [review]
Report header has been changed without reason

[Delivery Slip - Azure Interior - WH_OUT_00014 (2).pdf](https://github.com/user-attachments/files/15564960/Delivery.Slip.-.Azure.Interior.-.WH_OUT_00014.2.pdf)

**Comment by pilarvargas-tecnativa** [comment]
image
The functionality of repeating the header on all sheets is correct for me. 
Please check the tests.
Thanks!

**Comment by CarlosRoca13** [comment]
Changes done!

**Comment by CarlosRoca13** [comment]
image

Here is the result

**Review by pilarvargas-tecnativa — APPROVED** [review]
:+1:

**Review by Shide — APPROVED** [review]

**Pull request merged**
