### PR TITLE
15.0 mig stock quantity history location

### PR DESCRIPTION
**Pull request by ghost**
minor changes

### CODE REVIEW

**Comment by rousseldenis** [comment]
@nikolausweingartmair Thanks for this. Could you do a better PR title (like '[15.0][MIG] stock_quantity_history_location') as it would benefit reviewer's work

**Comment by rousseldenis** [comment]
@nikolausweingartmair We'll need to check #202 instead

**Comment by pedrobaeza** [comment]
Superseded by #272

**Pull request closed without merging**
