### PR TITLE
[15.0][MIG] stock_picking_report_undelivered_product: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36566

ping @carlosdauden @CarlosRoca13

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Pre-commit fix here https://github.com/OCA/stock-logistics-reporting/pull/242

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Comment by carlosdauden** [comment]
#242 merged. Rebase to fix pre-commit

**Comment by CarlosRoca13** [comment]
No need to rebse
The oca-bot will do it when merge

**Comment by carlosdauden** [comment]
Ok, I commented on it for the PR tests to turn green, but it is true that the problem is quite clear

image

**Comment by pedrobaeza** [comment]
@CarlosRoca13 are you reviewing the PR?

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
