### PR TITLE
[12.0][MIG] stock_account_valuation_report

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

CC @Eficent

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
FYI, I did a rebase in this branch.

**Comment by HviorForgeFlow** [comment]
@lreficent @bjeficent @aheficent @ageficent ready to review

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional review (with actual stock valuation entries)

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by HviorForgeFlow** [comment]
@rousseldenis ready to merge!

**Pull request merged**
